INFO 08-08 00:02:22 [__init__.py:245] No platform detected, vLLM is running on UnspecifiedPlatform
WARNING 08-08 00:02:41 [_custom_ops.py:20] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')

==================== Job Configuration ====================
Model path         : /leonardo_scratch/fast/try25_sgroi/models/c4ai
Dataset path       : /leonardo_scratch/fast/try25_sgroi/datasets/mc4_it
Prompt path        : /leonardo_work/try25_sgroi/VojoLe-LM/generation_prompt4.txt
ITA DB path        : er-italiano.db
SOR DB path        : er-sorianere.db
Batch size         : 25
Max context tokens : 40000
GPUs               : 0
============================================================

Tokenizing
Calculating statistics
{'Total sentences': 128366, 'Mean': 31544.594565539162, 'Standard deviation': 24.715641964741447, 'Max length': 31761, 'Min length': 31494}
